### ISSUE TITLE
@importing files from an addon

### ISSUE THREAD

**Issue by Ramblurr** [aexmachina/ember-cli-sass#107]
I have an addon I use as a shared-library for related styles and components shared among multiple projects to give a consistent look and feel.

Is there anyway to @import a scss file from the addon into an app's app.scss? I suspect not, but is this a feature worth considering?

Example:

```css
/* my-addon/addon/styles/variables.scss: */
$color-primary: red;
$color-secondary: blue;
```

```css
/* another-app/app/styles/app.scss: */
@import "path/to/my-addon/variables"

div {
  background-color: $color-primary;
}
```
