### ISSUE TITLE
All scss files recompiling when changes only happen in one of them

### ISSUE THREAD

**Issue by aristretto** [aexmachina/ember-cli-sass#119]
suppose I have 2 `scss` files, `shared.scss`, and `feature.scss` in my Ember-CLI project that are set up like so (hypothetical):

```scss
// shared.scss
$textColor: #eee;

html,
body {
  height: 100%;
  margin: 0;
  color: $textColor;
}
```

```scss
// feature.scss
.someFeature {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

`ember-cli-build.js` includes this:
```javascript
appConfig.outputPaths = {
	app: {
	// ...
		css: {
			'shared': 'shared.css',
			'feature': 'feature.css'
		}
	},
};
```

Both files have 0 dependency on each other, yet when I make a change in `feature.scss` it seems to trigger `SassCompiler` for all files (actual log output):

```bash
Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 996ms
TemplateCompiler                              | 956ms
SassCompiler                                  | 735ms
AutoprefixerFilter                            | 685ms
TreeMerger (preprocessedApp & templates)      | 642ms
SourceMapConcat: Concat: App Tests            | 581ms
SassCompiler                                  | 451ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (17)                                    | 1855ms (109 ms)
SassCompiler (4)                              | 1610ms (402 ms)
TemplateCompiler (4)                          | 1346ms (336 ms)
AutoprefixerFilter (1)                        | 685ms
TreeMerger (preprocessedApp & templates) (1)  | 642ms
SourceMapConcat: Concat: App Tests (1)        | 581ms

file changed feature.scss

Build successful - 5815ms.
```

Am I missing something? Why is `SassCompiler` listed twice?
