### ISSUE TITLE
Problem parsing Base64 embedded fonts

### ISSUE THREAD

**Issue by kylecoberly** [aexmachina/ember-cli-sass#41]
In the last CLI update, the sass compiler started tripping over embedded fonts:

```css
@font-face
{
    font-family: OpenSansBold;
    font-weight: normal;
    font-style: normal;
    src: url(data:font/ttf;base64,AAEAAAATAQAABAAwRFNJR5IYdDoAA1fcAAAVdEdERUYAJgOvAANTvAAAAB5HUE9TCzcPNwADU9wAAAA4R1NVQg4rPbcAA1QUAAADxk9TLzKidaEYAAABuAAAAGBjbWFwKasvaAAAELQAAAQaY3Z0IBMtGpQAAB2oAAAAqmZwZ227c6R1AAAU0AAAB+BnYXNwAAgAGwADU7AAAAAMZ2x5Zh1/yvQAACWsAAFLxGhlYWT34ccOAAABPAAAADZoaGVhDikKUgAAAXQAAAAkaG10eCTSBgAAAAIYAAAOmmtlcm5UKwl+AAFxcAABtjZsb2NhsttgKwAAHlQAAAdWbWF4cAU1Ah8AAAGYAAAAIG5hbWW8ZnsiAAMnqAAABdxwb3N0AkPvbAADLYQAACYrcHJlcMgJ/GsAABywAAAA+AABAAAAARmaOqk5s18PPPUACQgAAAAAAMlCF6AAAAAAyehKofsM/agKjQiNAAEACQACAAAAAAAAAAEAAAiN/agAAAqN+wz+eQqNAAEAAAAAAAAAAAAAAAAAAAOjAAEAAAOqAIoAFgBYAAUAAgAQAC8AXAAAAQABCwADAAEAAwUPArwABQAIBZoFMwAAAR8FmgUzAAAD0QBmAfwIAgILCAYDBQQCAgTgAALvQAAgWwAAACgAAAAAMUFTQwAgACD//QYf/hQAhAiNAlggAAGfAAAAAAReBbYAAAAgAAMEzQDBAAAAAAQUAAACFAAAAkoAdQPHAIUFKwAtBJEAWAc1AD8GAABSAiEAhQK2AFICtgA9BFwAPwSRAFgCUgA/ApMAPQJIAHUDTgAOBJEASgSRAHkEkQBOBJEATgSRACMEkQBkBJEASASRADcEkQBIBJEAQgJIAHUCUgA/BJEAWASRAFgEkQBYA9EABgctAGYFhQAABWAAuAUZAHcF7AC4BHsAuARkALgFywB3Bh8AuAMdAEICpv9oBVAAuASFALgHiwC4BoEAuAZeAHcFBgC4Bl4AdwVIALgEaABeBKIAKQYMAK4FMwAAB7wAAAVWAAAE/gAABKIAMQKmAI8DTgAMAqYAMwRCAAgDSv/8BNsBTATVAFYFEACgBB0AXAUQAFwEugBcAxkAKQSFAAYFQgCgAnEAkwJx/30E9gCgAnEAoAfbAKAFQgCgBPQAXAUQAKAFEABcA6IAoAP6AFwDeQAvBUIAmgSNAAAG2QAUBKAACgSNAAAD5wA3AycAHwRoAccDJwBSBJEAWAIUAAACSgB1BJEAjwSRAFIEkQBxBJEABgRoAccD4wBqBNsBFwaoAGQDEAAvBOwAUgSRAFgCkwA9BqgAZAQA//oDbQBcBJEAWAMIAC8DCAA7BNsBTAVIAKAFPQBxAkgAdQGk/9sDCABcAxsAOQTsAFIHDAAuBwwALgcMAFoD0QA9BYUAAAWFAAAFhQAABYUAAAWFAAAFhQAAB54AAAUZAHcEewC4BHsAuAR7AK8EewC4Ax0AKgMdAEIDHf/cAx0AOQXsAC8GgQC4Bl4AdwZeAHcGXgB3Bl4AdwZeAHcEkQCBBl4AdwYMAK4GDACuBgwArgYMAK4E/gAABQYAuAWwAKAE1QBWBNUAVgTVAFYE1QBWBNUAVgTVAFYHVgBWBB0AXAS6AFwEugBcBLoAXAS6AFwCcf+bAnEAkQJx/4YCcf/jBPQAXAVCAKAE9ABcBPQAXAT0AFwE9ABcBPQAXASRAFgE9ABcBUIAmgVCAJoFQgCaBUIAmgSNAAAFEACgBI0AAAWFAAAE1QBWBYUAAATVAFYFhQAABNUAVgUZAHcEHQBcBRkAdwQdAFwFGQB3BB0AXAUZAHcEHQBcBewAuAUQAFwF7AAvBTEAXAR7ALgEugBcBHsAuAS6AFwEewC4BLoAXAR7ALgEugBcBHsArwS6AFwFywB3BIUABgXLAHcEhQAGBcsAdwSFAAYFywB3BIUABgYfALgFQgCgBh8AAAVCAAQDHf/xAnH/mwMdAD8Ccf/pAx0ABwJx/68DHQBCAnEAKwMdAEICcQCgBcMAQgS6AJMCpv9oAnH/fQVQALgE9gCgBPYAoASFALgCcQCgBIUAuAJxAGMEhQC4AnEAoASFALgDbQCgBIUAAgKkAAAGgQC4BUIAoAaBALgFQgCgBoEAuAVCAKAGOwAGBoEAuAVCAKAGXgB3BPQAXAZeAHcE9ABcBl4AdwT0AFwHyQB3B9MAXAVIALgDogCgBUgAuAOiAGMFSAC4A6IAUwRoAF4D+gBcBGgAXgP6AFwEaABeA/oAXARoAF4D+gBcBKIAKQN5AC8EogApA3kALwSiACkDeQAvBgwArgVCAJoGDACuBUIAmgYMAK4FQgCaBgwArgVCAJoGDACuBUIAmgYMAK4FQgCaB7wAAAbZABQE/gAABI0AAAT+AAAEogAxA+cANwSiADED5wA3BKIAMQPnADcDEACgBJEAxQWFAAAE1QBWB54AAAdWAFYGXgB3BPQAXARoAF4D+gBcBNsAugTbALoE2wEbBNsA4wJxAJMEngFUAaYACgTbAM8EtACcBJ4B1wSeALoFhf/IAkgAdQUK/50Grv+dBBn/nQaw/8YGHf+IBkr/xgNC/8kFhQAABWAAuAR9ALgFRAA5BHsAuASiADEGHwC4Bl4AdwMdAEIFUAC4BTMAAAeLALgGgQC4BJEAUgZeAHcF9gC4BQYAuAS+AE4EogApBP4AAAbhAFwFVgAABwIAbQZKADcDHQA5BP4AAAUtAFwEcQBOBUIAoANCAKAFKQCPBS0AXAVIAKAEiwACBPQAXARxAE4D/ABcBUIAoATyAFwDQgCgBPYAoATsAAgFSACgBMMABgP8AFwE9ABcBekAGQTyAHkD/ABcBTkAXAROACkFKQCPBlYAXAS8/88GsgCPBucAbQNCAAwFKQCPBPQAXAUpAI8G5wBtBHsAuAZxACkEfQC4BWoAdwRoAF4DHQBCAx0AOQKm/2gH/gAQCAQAuAZxACkFYAC4BTkAAAX2ALgFhQAABRsAuAVgALgEfQC4Bh0ACgR7ALgHiwAABS8AXgaWALgGlgC4BWAAuAX2ABAHiwC4Bh8AuAZeAHcF9gC4BQYAuAUZAHcEogApBTkAAAbhAFwFVgAABj8AuAXTAG0IoAC4COkAuAXRAAAHPwC4BRsAuAVOAEgIjwC4BVL/9gTVAFYE+gBcBR0AoAPTAKAFUAAdBLoAXAb8AAAEcQBOBcMAoAXDAKAE9ACgBSkAAAbBAKAFTACgBPQAXAU3AKAFEACgBB0AXARtAC8EjQAABoMAXASgAAoFgQCgBT8AewfBAKAH4QCgBa4AAAbNAKAE6QCgBBkASgcEAKAEvgAABLoAXAVCAAQD0wCgBDEAXAP6AFwCcQCTAnH/5QJx/30HGwAABxsAoAVCAAQE9ACgBI0AAAVgAKAEpgC4BBkAoAe8AAAG2QAUB7wAAAbZABQHvAAABtkAFAT+AAAEjQAABAAAUggAAFIIAABSA0r//AG8ABkBvAAZAlQAPwG6ABkDjwAZA48AGQQlAD8EIQB7BDUAewMCAGIG1wB1Cj8APwIhAIUDxwCFAvIAUgLyAFIEjwB1AQr+dwNiAGYEkQAjBJEAUgcjALgEkQBCBlwAPwQpACkIOQCHBf4AEAZKADcE9ABmBwwAOgcMADsHDABaBwwAQwSmADsFRAA5Be4ApgUMACkEkQBYBGQAJQWoAHEDTAAABJEAWASRAFgEkQBWBJEAWASqAFgFiQApBYkAKQSeAGgCcf99BAABXgQAAV4EAAFOAwgAKQMIAAwDCABUAwgALQMIADsDCAAtAwgAKwQAAAAIAAAABAAAAAgAAAACqgAAAgAAAAFWAAAEeQAAAkgAAAGaAAAAzQAAAAAAAAAAAAAIAABUCAAAVAJx/30BvAAZBdsAKQUMAAAH/gAzB4sAuAfbAKAFhQAABNUAVgaw/nICqgBYAgAAeQigACkIoAApBpoAdwVvAFwHFACuBhQAmgAA/BYAAPzQAAD74AAA/NkAAPzZBHsAuAaWALgEugBcBcMAoAi0AHcHFAAGBWIAAAVMAAAHmgC4BmYAoAXXAAAFHwAACAoAuAc3AKAGbwApBPwAFAiWALgHCgCgBQ4AKQRxAB8HAgBtBrIAjwZeAHcE9ABcBbwAAATXAAAFvAAABNcAAAqNAHcJKQBcBrAAdwVvAFwItAB3Bx8AXAi0AHcHFAAGBWoAdwQxAFwE3wBoBHUAtASeAPQEngHNBJ4BywfpACkHpgApB1QAuAZqAKAE7gAvBOkABAUGALgFEACgBHkALwPuAAQF3wC4BNEAoAg7AAAHiQAABS8AXgRxAE4GDAC4BVIAoAVQALgEywCgBSUABAT2AAQF3QAABY8AAAa6ALgF8gCgBqwAuAYQAKAJAAC4Bx0AoAY3AHcFPwBcBRkAdwQdAFwEogApBGYALwT+AAAEmAAABP4AAASYAAAF8gAABR8ACgdxACkGVAAvBm8AbQXPAHsF0wBtBT8AewXTALgFVACgB5YAAAW4AAAHlgAABbgAAAMdAEIHiwAABvwAAAYUALgFSgCgBrQAEAXRAAAGHwC4BUwAoAbdALgF9ACgBdMAbQU/AHsISgC4B2gAoAMdAEIFhQAABNUAVgWFAAAE1QBWB54AAAdWAFYEewB2BLoAXAaJAKQEzwBcBokApATPAFwHiwAABvwAAAUvAF4EcQBOBLoAOQSmADkGlgC4BcMAoAaWALgFwwCgBl4AdwT0AFwGXgB3BPQAXAZeAHcE9ABcBU4ASAQZAEoFOQAABI0AAAU5AAAEjQAABTkAAASNAAAF0wBtBT8AewR9ALgD0wCgBz8AuAbNAKAEeQAvA+4ABAXbAAAFKQAKBVYAAASgAAoFGwBcBRAAXAdoAFwHYgBcB04AGQb2ADkFnAAZBUoATghEABAHewAACFgAuAeeAKAGZgB3BU4AXAYQACkF3wAvBS8AWARzAE4GiwAQBcsAAA
}
```

If I comment out the URL, it works. Otherwise it throws "expected a variable name (e.g. $x) or ')' for the parameter list for url"
