### ISSUE TITLE
You're putting me off my Bourbon :(

### ISSUE THREAD

**Issue by ZebraFlesh** [aexmachina/ember-cli-sass#43]
I'm using [Bourbon's linear-gradient mixin](http://bourbon.io/docs/#linear-gradient) and ember-cli-sass is generating incorrect css.  I provide the following input:

````scss
%some-color { 
  @include linear-gradient(to bottom, #151A20 0%, #0B0E11 100%);
}

.my-class {
  @extend %some-color
}
````
and I receive the following output from ember-cli-sass:
````css
.my-class {
  background-image: linear-gradient(to bottom,#151A20 0%, #0B0E11 100%, , , , , , , , ); }
````
whereas compiling with sass 3.4.13 running on ruby gives the correct css:
````css
.my-class {
  background-image: linear-gradient(to bottom,#151A20 0%, #0B0E11 100%); }
````
